### ISSUE TITLE
[metaissue] Three months goals for OpenCompose. (May 17th - August 8th)

### ISSUE THREAD

**Issue by surajssd** [redhat-developer/opencompose#131]
These are the issues that we are going to work in upcoming 3 months starting May 16th 2017.

* Goals
- [ ] [Support for command and args](https://github.com/redhat-developer/opencompose/issues/91)
- [ ] [OpenCompose files should be extendable](https://github.com/redhat-developer/opencompose/issues/120)
- [ ] [Support for multiple delivery environments](https://github.com/redhat-developer/opencompose/issues/47)
- [ ] [Spec design handbook](https://github.com/redhat-developer/opencompose/issues/132)
- [x] [Change env definition](https://github.com/redhat-developer/opencompose/issues/118)
- [ ] [secrets](https://github.com/redhat-developer/opencompose/issues/43)
- [ ] [healthchecks](https://github.com/redhat-developer/opencompose/issues/24)
- [ ] [Validating service name](https://github.com/redhat-developer/opencompose/issues/92)
- [ ] [Support for resources per container](https://github.com/redhat-developer/opencompose/issues/123)

* Stretch Goals
- [ ] [configmap](https://github.com/redhat-developer/opencompose/issues/124)
- [ ] [initcontainers](https://github.com/redhat-developer/opencompose/issues/126)
- [ ] [jobs](https://github.com/redhat-developer/opencompose/issues/44)
